import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Aegis Verified Report',
  description: 'AI-verified build report generated by Aegis',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, background: '#0A0A0C', color: '#E8E8F0', fontFamily: "'JetBrains Mono', monospace" }}>
        {children}
      </body>
    </html>
  );
}
