export default function HomePage() {
  return (
    <div style={{ maxWidth: 600, margin: '100px auto', textAlign: 'center', padding: '0 24px' }}>
      <div style={{ fontSize: 48, marginBottom: 16 }}>⬡</div>
      <h1 style={{ fontSize: 24, fontWeight: 700, letterSpacing: 4, color: '#E8E8F0', marginBottom: 8 }}>AEGIS VERIFIED</h1>
      <p style={{ color: 'rgba(232,232,240,0.5)', fontSize: 13 }}>
        Build verification reports are generated by the Aegis CLI.
      </p>
      <p style={{ color: 'rgba(232,232,240,0.3)', fontSize: 11, marginTop: 24 }}>
        Run <code style={{ color: '#7C6AFF' }}>aegis verify</code> to generate a shareable report.
      </p>
    </div>
  );
}
